# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
