# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_task_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
