# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('tasks', '0009_bid_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='final_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ratings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Rating'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Review'),
        ),
    ]
