# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='braintree_client_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='braintree_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_method_nonce',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_method_token',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
