# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_written_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
