# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20160101_2208'),
        ('accounts', '0011_auto_20151231_2242'),
        ('reviews', '0002_auto_20160101_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Contractor'),
        ),
        migrations.AddField(
            model_name='rating',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='review',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Contractor'),
        ),
        migrations.AddField(
            model_name='review',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
