# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20160101_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='msg',
            new_name='text',
        ),
    ]
