# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contractorprofile_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
