# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
