# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20151231_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='profile_pic',
            field=models.ImageField(blank=True, height_field='200', null=True, upload_to=b'', width_field='200'),
        ),
    ]
