# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20151231_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
