# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160105_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_method_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
