# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_payment_method_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='socket_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='socket_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
