# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20160111_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
