# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subcategory',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Subcategory'),
        ),
    ]
