# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20160111_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
