# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 16:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Phone numbers must be in +9999999999 format', regex='')]),
        ),
    ]
