# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraddress',
            table='addresses',
        ),
    ]
