# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20151224_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField(max_length=5)),
                ('street_address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(choices=[('AZ', 'AZ'), ('CA', 'CA'), ('TX', 'TX')], default='AZ', max_length=2)),
                ('zipcode', models.IntegerField(max_length=5)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
    ]
