# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='street_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
