# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20151226_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_img',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
