# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20160105_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Active', 'Active'), ('Completed', 'Completed'), ('Paid', 'Paid')], default='Open', max_length=30),
        ),
    ]
